### ISSUE TITLE
Ps3 controller vibration problem.

### ISSUE THREAD

**Issue by Narcotic82** [darthcloud/BlueRetro#197] opened 2022-03-02 21:21 UTC
Hi, I have a problem with the vibration of a Ps3 controller in a blueretro installed in the Ps2. When I test the controller in the Ps2 tester only the small vibration motor works. The strong motor does not work, it always activates the small one.

**Comment by darthcloud** [comment] 2022-03-02 21:25
Yes this is normal, duplicate of #20

**Closed by darthcloud** 2022-03-02 21:25 UTC

**Comment by Narcotic82** [comment] 2022-03-02 21:48
ok thanks, I just saw the post. I will wait for you to implement the dualshock functionality.
