### ISSUE TITLE
PC Engine GamepadAlt mode dpad doesn't work

### ISSUE THREAD

**Issue by mario-64** [darthcloud/BlueRetro#351] opened 2022-08-12 21:09 UTC
Testing a Retro-Bit Genesis bluetooth controller with the Humble PCE BT Adapter. Both on latest firmware. The controller works correctly when Mode = Gamepad (2 button). However, if you select Mode = GamepadAlt (6 button) the dpad doesn't work at all, even though dpad mapping is identical to Gamepad mode. I *think* button mapping works but can't really test since the dpad doesn't work.

**Comment by darthcloud** [comment] 2022-08-12 22:49
Which game you used?, 6 buttons mode only work in specific games.

**Comment by mario-64** [comment] 2022-08-12 23:31
Couldn’t get into a game. This is just on the SHDS3 Pro menu. Can’t navigate without dpad.

**Comment by darthcloud** [comment] 2022-08-12 23:36
You need to set 2 btns mode while in your SHDS3 menu, then once game started, switch to 6 buttons via web, save and hit reset on the adapter.

The problem is SHDS3 do not support 6 buttons mode in it's menu.

**Comment by mario-64** [comment] 2022-08-12 23:58
Really? Wow I didn’t know that. Will just stick with 2 button then. Thank you

**Comment by mario-64** [comment] 2022-08-13 00:52
I checked on the TO Discord and the SHDS3 Pro has no issues in the menu with 6 button controllers. 

"'ve had no problem with a wired Hori fighting commander. It's my main pce controller"
"i also have used my hori 6 button just fine in the menu"

**Comment by darthcloud** [comment] 2022-08-13 00:56
Is the controller set in 2 btns mode while they do this or in 6 buttons mode?

**Comment by mario-64** [comment] 2022-08-13 01:53
Doomy Dormer will be reaching out to you. He reproduced the issue using a DS5. He said it looks like the 6 button controller mapping is all messed up. Could you please re-open this? Thank you

**Comment by DoomyDoomer** [comment] 2022-08-13 02:52
I can confirm 6 Button mode doesn't work correctly in either SHDS3 PRO or Ever Drive menus but 2 button mode works fine. I also tested Street Fighter II on both and both have the same mapping issues. The options menu shows a 6 button controller but mapping isn't correct.

**Comment by darthcloud** [comment] 2022-08-16 11:30
Anyone with this issue can ping @DoomyDoomer directly for an hardware fix.

Closing here since not a software bug.

**Closed by darthcloud** 2022-08-16 11:30 UTC
