### ISSUE TITLE
PS2 and Dual Shock 3 - Pressure Sensitive Buttons not working

### ISSUE THREAD

**Issue by davedoc1984** [darthcloud/BlueRetro#389] opened 2022-09-01 11:23 UTC
When using A Dual Shock 3 (which has the pressure sensitive buttons on the front of the controller X, Square, Circle and Triangle) None of them work as they should do (e.g. the harder you press the button the more it accelerates in Gran Turismo 3).

This works fine with my Brook PS1/PS2 adapter when paired with a Dual Shock 3 but not with the BlueRetro PSX Adapter.

**Comment by darthcloud** [comment] 2022-09-01 11:25
It's not supported yet duplicate of #365

**Closed by darthcloud** 2022-09-01 11:25 UTC
