### ISSUE TITLE
Lag with multiple PowerA Wireless GameCube controllers

### ISSUE THREAD

**Issue by Arial-Bold** [darthcloud/BlueRetro#721] opened 2023-06-22 13:32 UTC
### BlueRetro firmware version

1.8

### BlueRetro firmware specification

HW1

### BlueRetro firmware variant

Universal

### BlueRetro hardware type

Internal install modkit

### Manufacturer

Lazerbear 

### System used

Nintendo GameCube

### Bluetooth controller brand & name

PowerA

### What is problem? (only list ONE problem per report)

Laggy controll input when multiple wireless controllers are connected 

### What did you expect to happen?

This to work like any other controller

**Comment by darthcloud** [comment] 2023-06-22 13:41
Duplicate of #146

**Closed by darthcloud** 2023-06-22 13:41 UTC
