### ISSUE TITLE
Internal GameCube mod has issues with PowerA Wireless GameCube controllers

### ISSUE THREAD

**Issue by TriVoxel** [darthcloud/BlueRetro#657] opened 2023-03-25 04:53 UTC
### BlueRetro firmware version

1.8.3

### BlueRetro firmware specification

HW2

### BlueRetro firmware variant

System specific

### BlueRetro hardware type

Internal install modkit

### Manufacturer

Lazer Bear

### System used

Nintendo GameCube

### Bluetooth controller brand & name

PowerA Wireless GameCube style controller for Switch

### What is problem? (only list ONE problem per report)

Player 1 works great, but adding additional controllers of this type will cause them to have severe latency issues and disconnects. Player 2 and onward will experience frequent and constant disconnects, as well as extremely high latency that is completely unplayable. Possibly linked to #586

### What did you expect to happen?

Normal multiplayer functionality.

**Comment by darthcloud** [comment] 2023-03-25 08:03
Duplicate of #146

**Closed by darthcloud** 2023-03-25 08:03 UTC
