### ISSUE TITLE
Rumble doesn't turn off on games N64 

### ISSUE THREAD

**Issue by 90sFavKi** [darthcloud/BlueRetro#615] opened 2023-02-18 01:24 UTC
### BlueRetro firmware version

1.8.3

### BlueRetro firmware specification

HW1

### BlueRetro firmware variant

System specific

### BlueRetro hardware type

External adapter with multiple hardwired cord

### Manufacturer

Grevh Tech Retro Rosseta 

### System used

Nintendo 64

### Bluetooth controller brand & name

Bralwer 64 NSO 

### What is problem? (only list ONE problem per report)

The rumble seems to not stop for certain games when using the brawler 64 NSO (switch) verison, game like tony Hawk it rumbles non stop after grinding on rails or you fall, games like WCW Mayham is unplayable because the rumble doesn't stop. 

### What did you expect to happen?

I excepted the rumble to perform like normal

**Comment by darthcloud** [comment] 2023-02-18 01:32
Duplicate of #548

**Closed by darthcloud** 2023-02-18 01:32 UTC
